move release version validation to release function

diff --git a/git-devbliss b/git-devbliss
--- a/git-devbliss
+++ b/git-devbliss
@@ -112,6 +112,14 @@ function branch {
 }
 
 function release {
+    
+    if echo $1 | grep -vE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
+        echo "Invalid version number" > /dev/stderr
+        exit 2
+    fi
+    
+    echo $1
+    
     check_repo_toplevel # neccessary to run makefile hooks
     git fetch --quiet origin
     local branch=`git rev-parse --abbrev-ref HEAD`
@@ -228,13 +236,8 @@ if [[ $# == 3 ]]; then
 elif [[ $# == 2 ]]; then
     if is_branch_command $1; then
         branch $1 $2
-    elif [[ $1 == "release" ]]; then
-        if echo $2 | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
-            release "$2"
-        else
-            echo "Invalid version number" > /dev/stderr
-            exit 2
-        fi
+    elif [[ $1 == "release" ]]; then        
+        release "$2"
     elif [[ $1 == "delete" ]]; then
         if [[ $2 == "-f" ]]; then
             delete "$2"
