check if repo is clean; adjusted version no regex

diff --git a/git-extensions/git-devbliss b/git-extensions/git-devbliss
--- a/git-extensions/git-devbliss
+++ b/git-extensions/git-devbliss
@@ -22,19 +22,24 @@ function help {
     echo '    delete:   Discard the current branch and delete the remote branch'
 }
 
+function is_repository_clean {
+    if [ $(git diff | wc -l) -eq 0 ]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
 function makefile_hooks {
     # reasonable targets are: changes, version, test (see: README.md)
     if [ ! -f Makefile ]; then
         echo "WARNING: No Makefile found. All make hooks have been skipped." >> /dev/stderr
         return
     fi
-    make $1
-    if [ $? -ne 0 ]; then
-        echo "WARNING: Makefile has no target named \"$1\". Please implement." >> /dev/stderr
-    fi
+    make $1 || echo "WARNING: Makefile has no target named \"$1\". Please implement." >> /dev/stderr
 }
 
-function isBranchCommand {
+function is_branch_command {
     local e
     for e in "${branches[@]}"; do [[ "$e" == "$1" ]] && return 0; done
     return 1
@@ -68,9 +73,14 @@ function branch {
 }
 
 function release {
+    is_repository_clean || echo "Error: Repository is not clean. Aborting ..." >> /dev/stderr && exit 1
     echo "Have these changes been reviewed?"
     echo "[enter / ctrl+c to cancel]"
     read
+    makefile_hooks version
+    if is_repository_clean; then :; else
+        git commit -am "version increment"
+    fi
     makefile_hooks test
     git commit --allow-empty -m "Release: $1"
     git tag $1
@@ -78,8 +88,11 @@ function release {
 }
 
 function finish {
-    makefile_hooks version
+    is_repository_clean || echo "Error: Repository is not clean. Aborting ..." >> /dev/stderr && exit 1
     makefile_hooks changes
+    if is_repository_clean; then :; else
+        git commit -am "changelog"
+    fi
     local branch=`git rev-parse --abbrev-ref HEAD`
     git push origin $branch
     hub pull-request
@@ -120,10 +133,10 @@ if [[ $# == 3 ]]; then
         help
     fi
 elif [[ $# == 2 ]]; then
-    if isBranchCommand $1; then
+    if is_branch_command $1; then
         branch $1 $2
     elif [[ $1 == "release" ]]; then
-        if echo $2 | grep -E '^[0-9]+\.[0-9]+(-[1-9][0-9]*)?$'; then
+        if echo $2 | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
             release $2
         else
             echo "Invalid version number" > /dev/stderr
