check if master is merged before finish

diff --git a/git-extensions/git-devbliss b/git-extensions/git-devbliss
--- a/git-extensions/git-devbliss
+++ b/git-extensions/git-devbliss
@@ -98,15 +98,20 @@ function release {
 }
 
 function finish {
+    local branch=`git rev-parse --abbrev-ref HEAD`
     if ! is_repository_clean; then
         echo "Error: Repository is not clean. Aborting." >> /dev/stderr
+        exit 1
+    fi
+    if git branch --no-merged master | grep "$branch"; then
+        echo "Error: Won't finish. Master is not merged into the current branch." > /dev/stderr
+        echo "Please do 'git pull origin master', make sure all conflicts are merged and try again." > /dev/stderr
         exit 1
     fi
     makefile_hooks changelog
     if ! is_repository_clean; then
         git commit -am "Ran git devbliss changelog hook"
     fi
-    local branch=`git rev-parse --abbrev-ref HEAD`
     git push origin $branch
     echo
     hub pull-request
