unistall target; makefile hook for changes

diff --git a/git-extensions/Makefile b/git-extensions/Makefile
--- a/git-extensions/Makefile
+++ b/git-extensions/Makefile
@@ -13,3 +13,30 @@ install:
 	@echo "    echo \"source /etc/bash_completion.d/git-devbliss\" >> ~/.profile"
 	@echo
 	@echo done
+
+.PHONY : uninstall
+uninstall:
+	@rm -f /usr/bin/git-devbliss
+	@rm -f /usr/bin/show-pulls
+	@rm -f /etc/bash_completion.d/git-devbliss
+
+define changelog_cmd
+	changelog="CHANGES.md"
+	echo $$EDITOR
+	if [ -z $$EDITOR ]; then
+		EDITOR=vi
+	fi
+	ch_hash=$$(sha1sum $$changelog)
+	$$EDITOR $$changelog
+	ch_hash_new=$$(sha1sum $$changelog)
+	echo $$ch_hash
+	echo $$ch_hash_new
+	if [ $$ch_hash == $$ch_hash_new ]; then
+		echo "Operation aborted due to missing changelog entry" > /dev/stderr
+		exit 1
+	fi
+endef
+export changelog_cmd
+.PHONY : changelog
+changelog:
+	@bash -c "$$changelog_cmd"
